package edu.uprm.ece.icom4015.jabrisca.client.views;

import edu.uprm.ece.icom4015.jabrisca.client.JabriscaController;

/**
 * 
 * @author EltonJohn
 */
public class Lobby extends JabriscaJPanel {

	/**
	 * Creates new form Lobby
	 */
	public Lobby() {
		super();
	}

	/**
	 * Creates new form Lobby
	 */
	public Lobby(JabriscaController listener) {
		super(listener);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jProgressBar1 = new javax.swing.JProgressBar();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel5 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jPanel4 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jPanel10 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jPanel11 = new javax.swing.JPanel();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel7 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jButton2 = new javax.swing.JButton();
		jPanel9 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jButton3 = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(876, 640));

		jPanel1.setPreferredSize(new java.awt.Dimension(670, 30));
		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
				javax.swing.BoxLayout.LINE_AXIS));

		jLabel2.setText("Status");
		jLabel2.setName("statusBar_status");
		jProgressBar1.setName("statusBar_progressBar");
		jPanel1.add(jLabel2);
		jPanel1.add(jProgressBar1);

		getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

		jPanel2.setPreferredSize(new java.awt.Dimension(640, 600));
		jPanel2.setLayout(new java.awt.BorderLayout());

		jPanel3.setPreferredSize(new java.awt.Dimension(150, 700));
		jPanel3.setLayout(null);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Lobby Chat");
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jPanel3.add(jLabel1);
		jLabel1.setBounds(0, 0, 150, 14);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setEditable(false);
		jTextArea1.setName("lobbyChat_display"); // NOI18N
		jScrollPane1.setViewportView(jTextArea1);

		jPanel3.add(jScrollPane1);
		jScrollPane1.setBounds(0, 20, 150, 340);

		jPanel5.setLayout(new java.awt.BorderLayout());

		jButton1.setText("Send");
		jButton1.setName("lobbyChat_send"); // NOI18N
		jPanel5.add(jButton1, java.awt.BorderLayout.LINE_END);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jTextArea2.setName("lobbyChat_message"); // NOI18N
		jScrollPane2.setViewportView(jTextArea2);

		jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		jPanel3.add(jPanel5);
		jPanel5.setBounds(0, 360, 150, 150);

		jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

		jPanel4.setPreferredSize(new java.awt.Dimension(490, 700));
		jPanel4.setLayout(new java.awt.BorderLayout());

		jPanel6.setPreferredSize(new java.awt.Dimension(520, 350));
		jPanel6.setLayout(new java.awt.BorderLayout());

		jPanel10.setPreferredSize(new java.awt.Dimension(520, 30));
		jPanel10.setLayout(null);

		jLabel5.setText("Games");
		jPanel10.add(jLabel5);
		jLabel5.setBounds(10, 10, 32, 14);

		jButton4.setText("Create New Game");
		jButton4.setName("games_create"); // NOI18N
		jPanel10.add(jButton4);
		jButton4.setBounds(350, 0, 170, 30);

		jPanel6.add(jPanel10, java.awt.BorderLayout.PAGE_START);

		jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11,
				javax.swing.BoxLayout.LINE_AXIS));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {
						{ "room01", "true", "false", "true", "true", "false", "false", "3/4" },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null } },
				new String[] { "RoomName", "Teams", "BlackHand", "CardSwap",
						"Surrender", "TimeLimit", "Tournament",
						"Players" }){
			@Override
			public boolean isCellEditable(int arg0, int arg1) {
				// TODO Auto-generated method stub
				return false;
			}
			
		});
		jTable1.setName("games_table"); // NOI18N
		jScrollPane5.setViewportView(jTable1);

		jPanel11.add(jScrollPane5);

		jPanel6.add(jPanel11, java.awt.BorderLayout.CENTER);

		jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

		jPanel7.setPreferredSize(new java.awt.Dimension(520, 350));
		jPanel7.setLayout(new java.awt.BorderLayout());

		jPanel8.setPreferredSize(new java.awt.Dimension(260, 600));
		jPanel8.setLayout(new java.awt.BorderLayout());

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("Players");
		jPanel8.add(jLabel3, java.awt.BorderLayout.PAGE_START);

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jTextArea3.setEditable(false);
		jTextArea3.setName("players_display"); // NOI18N
		jScrollPane3.setViewportView(jTextArea3);

		jPanel8.add(jScrollPane3, java.awt.BorderLayout.CENTER);

		jButton2.setText("Load More");
		jButton2.setName("players_load"); // NOI18N
		jPanel8.add(jButton2, java.awt.BorderLayout.PAGE_END);

		jPanel7.add(jPanel8, java.awt.BorderLayout.LINE_START);

		jPanel9.setLayout(new java.awt.BorderLayout());

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("LeaderBoards");
		jPanel9.add(jLabel4, java.awt.BorderLayout.PAGE_START);

		jTextArea4.setColumns(20);
		jTextArea4.setRows(5);
		jTextArea4.setEditable(false);
		jTextArea4.setName("leaderBoards_display"); // NOI18N
		jScrollPane4.setViewportView(jTextArea4);

		jPanel9.add(jScrollPane4, java.awt.BorderLayout.CENTER);

		jButton3.setText("Load More");
		jButton3.setName("leaderBoards_load"); // NOI18N
		jPanel9.add(jButton3, java.awt.BorderLayout.PAGE_END);

		jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

		jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

		jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

		getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

		jMenu1.setText("Options");

		jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Q,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem1.setText("Logout");
		jMenuItem1.setName("options_logout"); // NOI18N
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_H,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem2.setText("How to Play Brica");
		jMenuItem2.setName("howToPlay"); // NOI18N
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("My Scores");
		jMenuItem3.setName("myScores"); // NOI18N
		jMenu1.add(jMenuItem3);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		pack();
		setResizable(false);
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Lobby.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Lobby.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Lobby.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Lobby.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				JabriscaJPanel lobby = new Lobby();
				lobby.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JProgressBar jProgressBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	// End of variables declaration//GEN-END:variables
}
