 package edu.uprm.ece.icom4015.jabrisca.client.views;

import edu.uprm.ece.icom4015.jabrisca.client.JabriscaController;

/**
 *
 * @author EltonJohn
 */
public class NewGame extends JabriscaJPanel {

	/**
     * Creates new form NewGame
     */
    public NewGame() {
        super();
    }
    
    /**
     * Creates new form NewGame
     */
    public NewGame(JabriscaController listener) {
        super(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));

        jPanel1.setPreferredSize(new java.awt.Dimension(640, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jProgressBar1.setMaximumSize(new java.awt.Dimension(32767, 10));
        jProgressBar1.setName("statusBar_progressBar");
        jProgressBar1.setMinimumSize(new java.awt.Dimension(10, 10));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(146, 10));
        jPanel1.add(jProgressBar1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("status");
        jLabel1.setName("statusBar_status"); 
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setMaximumSize(new java.awt.Dimension(118, 249));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 249));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText("Room Name:");
        jPanel2.add(jLabel2);

        jTextField1.setText("RoomName");
        jTextField1.setName("roomName"); 
        jTextField1.setMaximumSize(new java.awt.Dimension(640, 30));
        jTextField1.setName("name"); // NOI18N
        jPanel2.add(jTextField1);

        jRadioButton6.setText("Play in Teams");
        jRadioButton6.setName("playInTeams"); // NOI18N
        jPanel2.add(jRadioButton6);

        jRadioButton2.setText("Win By Black Hand");
        jRadioButton2.setName("blackHand"); // NOI18N
        jPanel2.add(jRadioButton2);

        jRadioButton1.setText("Game Start Card Swap");
        jRadioButton1.setName("swapCard"); // NOI18N
        jPanel2.add(jRadioButton1);

        jRadioButton3.setText("Surrender");
        jRadioButton3.setName("surrender"); // NOI18N
        jPanel2.add(jRadioButton3);

        jRadioButton4.setText("Time Limit Per Turn");
        jRadioButton4.setName("timed"); // NOI18N
        jPanel2.add(jRadioButton4);

        jRadioButton5.setText("Tournament Mode");
        jRadioButton5.setName("tournamentMode"); // NOI18N
        jPanel2.add(jRadioButton5);

        jButton2.setText("Create Room!");
        jButton2.setName("createRoom"); // NOI18N
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("How to Play Brisca");
        jMenuItem1.setName("howToPlay"); // NOI18N
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setResizable(false);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGame(new JabriscaController()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
